"""change type seasons.series_all and add titles.cover

Revision ID: 128f180fc169
Revises: d944f51ea1b2
Create Date: 2025-01-24 14:35:02.589721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '128f180fc169'
down_revision = 'd944f51ea1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.alter_column('series_all',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.drop_column('cover')

    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.alter_column('series_all',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
