"""not uniq seria_url

Revision ID: 4a850baf873f
Revises: 9680848ce3c4
Create Date: 2025-02-17 11:56:23.056846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a850baf873f'
down_revision = '9680848ce3c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index('url', ['url'], unique=True)

    # ### end Alembic commands ###
