"""Add column update_on in seasons table

Revision ID: 517adb7c0261
Revises: 128f180fc169
Create Date: 2025-02-07 09:21:32.004173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517adb7c0261'
down_revision = '128f180fc169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_on', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_column('update_on')

    # ### end Alembic commands ###
