"""Add table users_titles

Revision ID: 9680848ce3c4
Revises: 517adb7c0261
Create Date: 2025-02-13 11:40:10.226992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9680848ce3c4'
down_revision = '517adb7c0261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('seria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seria_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_titles')
    # ### end Alembic commands ###
